### ISSUE TITLE
Unable to use the app

### ISSUE THREAD

**Issue by hussain3152** [nilinyi/WorldTraveler#1]
Unable to understand how the app works.
Opens only blank view controller, nothing else.

**Comment by nilinyi** [comment]
Yeah, it is just  a blank view. You should run it in you real device. And when you run, you also need to simulate the location in Xcode as I said in the Readme.  Then you can tap home button(do not quit this app nor plug your wire) and switch to other app that use location service and you can see the fake location. So, the key is you need to keep this “blank" app in background and connected to Xcode.

**Comment by hussain3152** [comment]
Hello Linyi,

I got the point.
Just a query can we do this without simulating location(without debug mode).
Thanks for the support.

**Comment by nilinyi** [comment]
You are welcome. 
It is impossible because Apple do not allow location simulation without Xcode. (The trick is to simulate the location via our customized location file, but we cannot locate and revise this file in real device without Xcode.) I have heard that you can do this in jail-brokened iPhone, but I haven’t tried yet.
